import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  // title:{
  //   default:"Next.js Tutorial - Codevolution",
  //   template:"%s | Codevolution",
  //   absolute:"This is used when the chilld does not want any meta deta of parent it is used in child file only not here"
  // },
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <header
          style={{
            backgroundColor:"lightblue",
            padding:"1rem"
          }}
        >
          <p>Header</p>
        </header>
        {children}
        <footer
          style={{
            backgroundColor:"ghostwhite",
            padding:"1rem",
          }}
        >
          <p>Footer</p>
        </footer>
      </body>
    </html>
  );
}
